import { ChainName } from '@hyperlane-xyz/sdk';
import type { AnnotatedTransaction, SafeTransactionBatch } from './types';

/**
 * Convert annotated transactions to Safe transaction batch format
 * Validates all transaction data before conversion
 * @param transactions - Array of annotated transactions from SDK
 * @param chainId - Numeric chain ID
 * @param chainName - Human-readable chain name
 * @param safeAddress - Optional Safe address for metadata
 * @returns Safe-compatible transaction batch
 * @throws Error if validation fails
 */
export function convertToSafeBatch(
  transactions: AnnotatedTransaction[],
  chainId: number,
  chainName: ChainName,
  safeAddress?: string
): SafeTransactionBatch {
  // Validate all transactions
  transactions.forEach((tx, i) => {
    if (!tx.to || !/^0x[a-fA-F0-9]{40}$/.test(tx.to)) {
      throw new Error(`Invalid 'to' address at transaction ${i}: ${tx.to}`);
    }
    if (tx.data && !/^0x[a-fA-F0-9]*$/.test(tx.data)) {
      throw new Error(`Invalid 'data' at transaction ${i}: must be valid hex`);
    }
  });

  return {
    version: '1.0',
    chainId: chainId.toString(),
    createdAt: Date.now(),
    meta: {
      name: `Hyperlane Warp Update - ${chainName}`,
      description: `Warp route configuration update for ${chainName}. ${transactions.length} transaction(s). Generated by Hyperlane Deploy UI.`,
      txBuilderVersion: '1.18.0',
      createdFromSafeAddress: safeAddress,
    },
    transactions: transactions.map(tx => ({
      to: tx.to,
      value: tx.value?.toString() || '0',
      data: tx.data || '0x',
      operation: 0, // Always Call (0) for warp updates, never DelegateCall (1)
      annotation: tx.annotation // Preserve SDK description of what this tx does
    }))
  };
}
